# Site settings
title: "#mapSwazi: "
description: "#mapSwazi"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://1papaya.github.io/mapSwazi" # the base hostname & protocol for your site

contact:
  email: "mapSwazi@gmail.com"
  whatsapp: "https://bit.ly/2F9sd2P"

color: "purple"
collections_dir: "collections"

permalink: pretty

exclude:
  - .cache
  - node_modules

plugins:
  - jekyll-menus

collections:
  supporters:
    output: false
  news:
    output: true
  instructions:
    output: true

exclude:
  - assets/js/dev.js
  - assets/js/mapSwazi*.js
  - assets/js/*.json

# defaults
defaults:
  -
    scope:
      path: ""
      type: "supporters"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "news"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "instructions"
    values:
      layout: "instruction"

# Build settings
Markdown: kramdown

# SASS settings
sass:
  sass_dir: assets/css
  style: compressed
